repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: bamboo-specs/bamboo.yaml
      - id: sort-simple-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-xml

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.272
    hooks:
      - id: ruff
        # Ignoring unused imports within __init__.py files.
        args: [--per-file-ignores, '*__init__.py:F401', --fix]


  - repo: https://github.com/pycqa/pydocstyle
    rev: "6.3.0"
    hooks:
      - id: pydocstyle
        args: [ "--convention=google" ]
        files: bigym|examples|vr|demonstrations|tools

  - repo: https://github.com/lsst-ts/pre-commit-xmllint
    rev: v1.0.0
    hooks:
      - id: format-xmllint
